### ISSUE TITLE
Can't resolve `babel-loader`/Can't find module `@babel/plugin-syntax-dynamic-import`

### ISSUE THREAD

**Issue by CassandraNewell** [LaunchAcademy/make_it_so#62]
Mike Wellman (BOS24) is unable to deploy a new app to heroku. 
```
ERROR in Entry module not found: Error: Can't resolve 'babel-loader'
``` 
The app was created using the most recent version of make_it_so. 

He tried include installing babel-loader and using resolveLoader with the specific path. 

```
 "dependencies": {
    "@rails/webpacker": "3.5",
    "prop-types": "~15.6.0",
    "react": "~16.8.0",
    "react-dom": "~16.8.0",
    "react-router": "3.2.1",
    "react-vis": "^1.11.7",
    "redbox-react": "1.6.0"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.11.1",
    "@babel/core": "^7.5.5",
    "@babel/plugin-proposal-class-properties": "^7.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "webpack-cli": "^2.0.10",
    "babel-jest": "~23.4.0",
    "enzyme": "~3.10.0",
    "enzyme-adapter-react-16": "~1.14.0",
    "fetch-mock": 

- [ ] "~5.13.1",

    "jest": "~23.4.1"
  }
```

**Comment by CassandraNewell** [comment]
Need to 
* remove babel-loader dep in package.json
* will then encounter `Unknown plugin "@babel/plugin-syntax-dynamic-import"`, https://stackoverflow.com/questions/55009961/unknown-plugin-in-babelrc-when-running-jest
* need to upgrade to Jest 24

**Comment by CassandraNewell** [comment]
The process ⬆️didn't resolve the issue. I also installed babel-jest as a dev dependency. Error is still

```
ERROR in ./app/javascript/packs/application.js
remote:        Module build failed: ReferenceError: Unknown plugin "@babel/syntax-dynamic-import" specified in "/tmp/build_2bb9c073fac6b630141101f08287c086/.babelrc" at 0, attempted to resolve relative to "/tmp/build_2bb9c073fac6b630141101f08287c086"
remote:            at /tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
remote:            at Array.map (<anonymous>)
remote:            at Function.normalisePlugins (/tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
remote:            at OptionManager.mergeOptions (/tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
remote:            at OptionManager.init (/tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
remote:            at File.initOptions (/tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-core/lib/transformation/file/index.js:212:65)
remote:            at new File (/tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-core/lib/transformation/file/index.js:135:24)
remote:            at Pipeline.transform (/tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
remote:            at transpile (/tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-loader/lib/index.js:50:20)
remote:            at /tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-loader/lib/fs-cache.js:118:18
remote:            at ReadFileContext.callback (/tmp/build_2bb9c073fac6b630141101f08287c086/node_modules/babel-loader/lib/fs-cache.js:31:21)
remote:            at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
```

**Comment by CassandraNewell** [comment]
Nope, just kidding -- the issue with babel-loader is actually that it needs to be a dependency, not a dev dependency.

**Comment by CassandraNewell** [comment]
I'm chasing my tail. Current theory: need to switch to babel.conf.js: https://jestjs.io/docs/en/getting-started#using-babel

**Comment by CassandraNewell** [comment]
Working branch: `fix-babel-loaders`. 
Heroku app with jest codebase (will not compile): https://dashboard.heroku.com/apps/test-with-jest

@dpickett : I've been going around in circles with this issue. When I clear up the babel-loader issue, I run into the @babel/plugin-syntax-dynamic-import issue and vice versa. Could use another set of eyes/some patented Padre Pickett wisdom.

Really wish I could come up with a p-word for wisdom.

**Comment by dpickett** [comment]
ok so this has to do with Rails' opinions of how babel should be configured vs. what our optimal react stack looks like. Unfortunately it looks like webpacker defines multiple babel plugins as runtime dependencies. 

When I create a new app with webpacker, here's the `babel.config.js`:

```javascript
module.exports = function(api) {
  var validEnv = ['development', 'test', 'production']
  var currentEnv = api.env()
  var isDevelopmentEnv = api.env('development')
  var isProductionEnv = api.env('production')
  var isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.'
    )
  }

  return {
    presets: [
      isTestEnv && [
        require('@babel/preset-env').default,
        {
          targets: {
            node: 'current'
          }
        }
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        require('@babel/preset-env').default,
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3,
          modules: false,
          exclude: ['transform-typeof-symbol']
        }
      ],
      [
        require('@babel/preset-react').default,
        {
          development: isDevelopmentEnv || isTestEnv,
          useBuiltIns: true
        }
      ]
    ].filter(Boolean),
    plugins: [
      require('babel-plugin-macros'),
      require('@babel/plugin-syntax-dynamic-import').default,
      isTestEnv && require('babel-plugin-dynamic-import-node'),
      require('@babel/plugin-transform-destructuring').default,
      [
        require('@babel/plugin-proposal-class-properties').default,
        {
          loose: true
        }
      ],
      [
        require('@babel/plugin-proposal-object-rest-spread').default,
        {
          useBuiltIns: true
        }
      ],
      [
        require('@babel/plugin-transform-runtime').default,
        {
          helpers: false,
          regenerator: true,
          corejs: false
        }
      ],
      [
        require('@babel/plugin-transform-regenerator').default,
        {
          async: false
        }
      ],
      isProductionEnv && [
        require('babel-plugin-transform-react-remove-prop-types').default,
        {
          removeImport: true
        }
      ]
    ].filter(Boolean)
  }
}
```

And the resultant `package.json`:

```json
{
  "name": "tst_webpacker",
  "private": true,
  "dependencies": {
    "@babel/preset-react": "^7.0.0",
    "@rails/actioncable": "^6.0.0-alpha",
    "@rails/activestorage": "^6.0.0-alpha",
    "@rails/ujs": "^6.0.0-alpha",
    "@rails/webpacker": "^4.0.7",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "prop-types": "^15.7.2",
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "turbolinks": "^5.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3.8.2"
  }
}
```

What I would do is create a new rails app with the rails version we want, and effectively steal / mimic the resultant `package.json` and `babel.config.js`. That will likely get things working for us.
